# Generated by Django 6.0.5 on 2026-05-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='function',
            field=models.CharField(choices=[('Checkout', 'Checkout'), ('Kitchen', 'Kitchen')], max_length=10),
        ),
    ]
