# Generated by Django 6.0.5 on 2026-07-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='function',
            field=models.CharField(choices=[('checkout', 'Checkout'), ('kitchen', 'Kitchen')], max_length=10),
        ),
    ]
