# Generated by Django 6.0.5 on 2026-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='function',
            field=models.CharField(choices=[('checkout', 'Checkout'), ('kitchen', 'Kitchen')], max_length=10),
        ),
    ]
