# Generated by Django 6.0.5 on 2026-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='point_terminal_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
