# Generated by Django 6.0.5 on 2026-06-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_point_terminal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='point_terminal_id',
            field=models.CharField(max_length=255),
        ),
    ]
