# Generated by Django 6.0.5 on 2026-06-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_point_terminal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='point_terminal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
