# Generated by Django 6.0.5 on 2026-07-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_blocked_until_device_is_blocked_and_more'),
        ('devices', '0006_alter_device_point_terminal_id'),
    ]

    operations = [
    ]
