# Generated by Django 6.0.5 on 2026-05-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Lanches', 'Lanches'), ('Pratos Principais', 'Pratos Principais'), ('Petiscos', 'Petiscos'), ('Sobremesas', 'Sobremesas'), ('Bebidas', 'Bebidas'), ('Saladas', 'Saladas'), ('Massas', 'Massas'), ('Hambúrgueres', 'Hambúrgueres'), ('Pizzas', 'Pizzas')])),
            ],
        ),
    ]
