# Generated by Django 6.0.5 on 2026-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='restaurant_menu/default.png', upload_to='restaurant/menu'),
        ),
    ]
