# Generated by Django 6.0.5 on 2026-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='image',
            new_name='item_image',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(default='Oi', max_length=1000),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_ingredients',
            field=models.TextField(default='eae', max_length=1000),
        ),
    ]
