# Generated by Django 6.0.5 on 2026-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0003_rename_category_menuitem_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_ingredients',
            field=models.TextField(max_length=1000),
        ),
    ]
